// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbgsuiaxztcbunhwwyxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZ3N1aWF4enRjYnVuaHd3eXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTc4MjEsImV4cCI6MjA2MzA3MzgyMX0.8AP9d4tU6Y0VKmGSJkcyP8o0oxR8YDmUD_y_V3tkikc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);